env:
  node: true
  jest: true
extends:
  - 'airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:jest/recommended'
parser: 'babel-eslint'

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-console: 0
